# Generated by Django 4.0.2 on 2022-02-22 22:03

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('no_of_ctns_ordered', models.CharField(max_length=200)),
                ('no_of_cbm_ordered', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('shipping_mark', models.CharField(max_length=500)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
