# Generated by Django 4.0.2 on 2022-02-20 20:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
